[theme]
primaryColor="#32CD32"  # Light green accents
backgroundColor="#001F3F"  # Dark blue background
secondaryBackgroundColor="#003366"  # Slightly lighter dark blue for secondary elements
textColor="#FFFFFF"  # White text
font="sans serif"
